### ISSUE TITLE
The image doesn't render correctly in vte based terminals.

### ISSUE THREAD

**Issue by dylanaraps** [dylanaraps/fetch.sh#5]
I've already found a fix, adding a sleep of 0.2s right before we draw the image solves the problem in all vte based terminals I tried.

The only issue is trying to detect whether or not we're in a vte based terminal.

**Comment by qualious** [comment]
I can't seem to apply the solution in gnome-terminal or termite (both vte-based).
I tried adding :
```
    sleep 0.2s
    sleep 0.2
```
after these lines
https://github.com/dylanaraps/fetch.sh/blob/master/fetch.sh#L569
https://github.com/dylanaraps/fetch.sh/blob/master/fetch.sh#L498

either of them worked. Can you elobrate on this issue ? Thanks.

Also, this how it looks like in urxvt:

![2016-01-03-012754_796x295_scrot](https://cloud.githubusercontent.com/assets/11707431/12076554/59a48dae-b1b9-11e5-9aed-2406732b93e8.png)

This is how it looks in XTerm (correct output):

![2016-01-02-124636_1920x1080_scrot](https://cloud.githubusercontent.com/assets/11707431/12076563/b24196d2-b1b9-11e5-9c13-69bc4fc3d8d9.png)

Gnome-terminal:
![2016-01-02-124355_1920x1080_scrot](https://cloud.githubusercontent.com/assets/11707431/12076565/c186b17c-b1b9-11e5-9dcd-f64717920e92.png)

hope these helps! Since your script is using w3m and these terminals are infamous for their w3m-img quality (aside from XTerm), i tried it anyways to save some time. Hope these helps!

**Comment by dylanaraps** [comment]
I see why it isn't working now. 

What happens is that the image is displayed faster than the text which causes the text to erase the image.

I'm working on a fix locally but in the meantime try adding a sleep like this to line 569 and It should draw correctly.  

```sh
# If this still doesn't work try increasing it.
sleep 1s
```

**Comment by dylanaraps** [comment]
I've fixed the issue. 

I'll push it to master either later today or tomorrow.

**Comment by dylanaraps** [comment]
Fixed.
